---
title: "R Class 2023/09/08"
author: "STANLEY SAYIANKA SAITET"
date: "2023-08-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd('/home/ncworkforce/Documents/CEMA/data/shapefiles')

library(pacman)
p_load(dplyr, stringr, lubridate, ggplot2, sf, readxl)
```

<!-- sudo aptitude install libgdal-dev -->
<!-- devtools::install_github("r-spatial/sf") -->

```{r, calldata, include=FALSE}
county_data <- read_sf('County.shp')
density_data <- read_xlsx('Density.xlsx')
# county_data <- st_read('County.shp')
```

```{r plot}
ggplot(county_data)+
  geom_sf(aes(geometry = geometry))+
  labs(title = 'Map: Density of physician HWF per 10,000 population', x='', y = '', fill = 'Physician Density')+
  scale_fill_gradient(low = 'tomato', high = 'green')+
  theme_void()
```

## Finding if all the county names match

```{r }
density_counties <- unique(density_data$county)
shape_counties <- unique(county_data$county)
density_counties[which(!density_counties %in% shape_counties)]

# recoding the two in the density data
# Keiyo-Marakwet, Murang'A
```

## Merging the two datasets

```{r merge-data}
density_data <- density_data |>
  mutate(county = recode(county, "Keiyo-Marakwet"="Elgeyo Marakwet", "Murang'A"="Muranga"))

d1 <- merge(density_data, county_data, by.x = 'county', by.y = 'name', all = T)
# githubtoken: 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
# full_join(density_data, county_data, by = c('county'='name'))
```

```{r plot-density-data}

```









